### ISSUE TITLE
Plantable Pine, Oak & Hickory Trees

### ISSUE THREAD

**Issue by vlad1492** [LambdaSix/Wild-Living#4]

**Comment by LambdaSix** [comment]
Currently I think that only includes Hickory trees and Pine Trees.

While Acorns should drop from harvesting Oak trees, they currently don't, I could probably add that pretty easily though. I suspect oak has no harvest actions because it's intended to be a generic lumber tree.

I will likely introduce plantable Hickory and Pine trees using the same existing sapling mechanic, because Hickory root is an important source of salt for wilderness runs, and Pine is an important source of pine boughs for sealing & shelter materials.

What is on my todo list is plantable young trees from a generic sapling cut from other young saplings (4 cuttings and it destroys the young tree) -- so I'll probably include oak trees as replantable and add harvesting of acorns in Autumn from them.
